// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetInitialLogs() {
  return window['go']['main']['App']['GetInitialLogs']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function LoadPreviousChunk() {
  return window['go']['main']['App']['LoadPreviousChunk']();
}

export function ProcessDrop(arg1) {
  return window['go']['main']['App']['ProcessDrop'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartTailing(arg1) {
  return window['go']['main']['App']['StartTailing'](arg1);
}

export function StopTailing() {
  return window['go']['main']['App']['StopTailing']();
}
