// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function GetInitialLogs():Promise<Array<models.LogEntry>>;

export function GetVersion():Promise<string>;

export function ListFiles(arg1:string):Promise<Array<models.FileInfo>>;

export function LoadPreviousChunk():Promise<Array<models.LogEntry>>;

export function ProcessDrop(arg1:string):Promise<models.DropResult>;

export function SelectFolder():Promise<string>;

export function StartTailing(arg1:string):Promise<void>;

export function StopTailing():Promise<void>;
